//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://app.fpml.org/ws", ConfigurationName="ServiceReference.WebInterfaceSoap")]
    public interface WebInterfaceSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://app.fpml.org/ws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://app.fpml.org/ws/StartSession", ReplyAction="*")]
        ServiceTest.ServiceReference.StartSessionResponse StartSession(ServiceTest.ServiceReference.StartSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.fpml.org/ws/EndSession", ReplyAction="*")]
        void EndSession();
        
        // CODEGEN: Generating message contract since element name document from namespace http://app.fpml.org/ws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://app.fpml.org/ws/SubmitMessage", ReplyAction="*")]
        ServiceTest.ServiceReference.SubmitMessageResponse SubmitMessage(ServiceTest.ServiceReference.SubmitMessageRequest request);
        
        // CODEGEN: Generating message contract since element name RetrieveMessageResult from namespace http://app.fpml.org/ws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://app.fpml.org/ws/RetrieveMessage", ReplyAction="*")]
        ServiceTest.ServiceReference.RetrieveMessageResponse RetrieveMessage(ServiceTest.ServiceReference.RetrieveMessageRequest request);
        
        // CODEGEN: Generating message contract since element name requestId from namespace http://app.fpml.org/ws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://app.fpml.org/ws/RetrieveResponseMessage", ReplyAction="*")]
        ServiceTest.ServiceReference.RetrieveResponseMessageResponse RetrieveResponseMessage(ServiceTest.ServiceReference.RetrieveResponseMessageRequest request);
        
        // CODEGEN: Generating message contract since element name message from namespace http://app.fpml.org/ws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://app.fpml.org/ws/ProcessMessage", ReplyAction="*")]
        ServiceTest.ServiceReference.ProcessMessageResponse ProcessMessage(ServiceTest.ServiceReference.ProcessMessageRequest request);
        
        // CODEGEN: Generating message contract since element name RetrieveNotificationMessageResult from namespace http://app.fpml.org/ws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://app.fpml.org/ws/RetrieveNotificationMessage", ReplyAction="*")]
        ServiceTest.ServiceReference.RetrieveNotificationMessageResponse RetrieveNotificationMessage(ServiceTest.ServiceReference.RetrieveNotificationMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartSessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartSession", Namespace="http://app.fpml.org/ws", Order=0)]
        public ServiceTest.ServiceReference.StartSessionRequestBody Body;
        
        public StartSessionRequest() {
        }
        
        public StartSessionRequest(ServiceTest.ServiceReference.StartSessionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://app.fpml.org/ws")]
    public partial class StartSessionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public StartSessionRequestBody() {
        }
        
        public StartSessionRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartSessionResponse", Namespace="http://app.fpml.org/ws", Order=0)]
        public ServiceTest.ServiceReference.StartSessionResponseBody Body;
        
        public StartSessionResponse() {
        }
        
        public StartSessionResponse(ServiceTest.ServiceReference.StartSessionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://app.fpml.org/ws")]
    public partial class StartSessionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool StartSessionResult;
        
        public StartSessionResponseBody() {
        }
        
        public StartSessionResponseBody(bool StartSessionResult) {
            this.StartSessionResult = StartSessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitMessage", Namespace="http://app.fpml.org/ws", Order=0)]
        public ServiceTest.ServiceReference.SubmitMessageRequestBody Body;
        
        public SubmitMessageRequest() {
        }
        
        public SubmitMessageRequest(ServiceTest.ServiceReference.SubmitMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://app.fpml.org/ws")]
    public partial class SubmitMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string document;
        
        public SubmitMessageRequestBody() {
        }
        
        public SubmitMessageRequestBody(string document) {
            this.document = document;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitMessageResponse", Namespace="http://app.fpml.org/ws", Order=0)]
        public ServiceTest.ServiceReference.SubmitMessageResponseBody Body;
        
        public SubmitMessageResponse() {
        }
        
        public SubmitMessageResponse(ServiceTest.ServiceReference.SubmitMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://app.fpml.org/ws")]
    public partial class SubmitMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SubmitMessageResult;
        
        public SubmitMessageResponseBody() {
        }
        
        public SubmitMessageResponseBody(string SubmitMessageResult) {
            this.SubmitMessageResult = SubmitMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveMessage", Namespace="http://app.fpml.org/ws", Order=0)]
        public ServiceTest.ServiceReference.RetrieveMessageRequestBody Body;
        
        public RetrieveMessageRequest() {
        }
        
        public RetrieveMessageRequest(ServiceTest.ServiceReference.RetrieveMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://app.fpml.org/ws")]
    public partial class RetrieveMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool wait;
        
        public RetrieveMessageRequestBody() {
        }
        
        public RetrieveMessageRequestBody(bool wait) {
            this.wait = wait;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveMessageResponse", Namespace="http://app.fpml.org/ws", Order=0)]
        public ServiceTest.ServiceReference.RetrieveMessageResponseBody Body;
        
        public RetrieveMessageResponse() {
        }
        
        public RetrieveMessageResponse(ServiceTest.ServiceReference.RetrieveMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://app.fpml.org/ws")]
    public partial class RetrieveMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetrieveMessageResult;
        
        public RetrieveMessageResponseBody() {
        }
        
        public RetrieveMessageResponseBody(string RetrieveMessageResult) {
            this.RetrieveMessageResult = RetrieveMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveResponseMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveResponseMessage", Namespace="http://app.fpml.org/ws", Order=0)]
        public ServiceTest.ServiceReference.RetrieveResponseMessageRequestBody Body;
        
        public RetrieveResponseMessageRequest() {
        }
        
        public RetrieveResponseMessageRequest(ServiceTest.ServiceReference.RetrieveResponseMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://app.fpml.org/ws")]
    public partial class RetrieveResponseMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool wait;
        
        public RetrieveResponseMessageRequestBody() {
        }
        
        public RetrieveResponseMessageRequestBody(string requestId, bool wait) {
            this.requestId = requestId;
            this.wait = wait;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveResponseMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveResponseMessageResponse", Namespace="http://app.fpml.org/ws", Order=0)]
        public ServiceTest.ServiceReference.RetrieveResponseMessageResponseBody Body;
        
        public RetrieveResponseMessageResponse() {
        }
        
        public RetrieveResponseMessageResponse(ServiceTest.ServiceReference.RetrieveResponseMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://app.fpml.org/ws")]
    public partial class RetrieveResponseMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetrieveResponseMessageResult;
        
        public RetrieveResponseMessageResponseBody() {
        }
        
        public RetrieveResponseMessageResponseBody(string RetrieveResponseMessageResult) {
            this.RetrieveResponseMessageResult = RetrieveResponseMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessMessage", Namespace="http://app.fpml.org/ws", Order=0)]
        public ServiceTest.ServiceReference.ProcessMessageRequestBody Body;
        
        public ProcessMessageRequest() {
        }
        
        public ProcessMessageRequest(ServiceTest.ServiceReference.ProcessMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://app.fpml.org/ws")]
    public partial class ProcessMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string message;
        
        public ProcessMessageRequestBody() {
        }
        
        public ProcessMessageRequestBody(string message) {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessMessageResponse", Namespace="http://app.fpml.org/ws", Order=0)]
        public ServiceTest.ServiceReference.ProcessMessageResponseBody Body;
        
        public ProcessMessageResponse() {
        }
        
        public ProcessMessageResponse(ServiceTest.ServiceReference.ProcessMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://app.fpml.org/ws")]
    public partial class ProcessMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ProcessMessageResult;
        
        public ProcessMessageResponseBody() {
        }
        
        public ProcessMessageResponseBody(string ProcessMessageResult) {
            this.ProcessMessageResult = ProcessMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveNotificationMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveNotificationMessage", Namespace="http://app.fpml.org/ws", Order=0)]
        public ServiceTest.ServiceReference.RetrieveNotificationMessageRequestBody Body;
        
        public RetrieveNotificationMessageRequest() {
        }
        
        public RetrieveNotificationMessageRequest(ServiceTest.ServiceReference.RetrieveNotificationMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://app.fpml.org/ws")]
    public partial class RetrieveNotificationMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool wait;
        
        public RetrieveNotificationMessageRequestBody() {
        }
        
        public RetrieveNotificationMessageRequestBody(bool wait) {
            this.wait = wait;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveNotificationMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveNotificationMessageResponse", Namespace="http://app.fpml.org/ws", Order=0)]
        public ServiceTest.ServiceReference.RetrieveNotificationMessageResponseBody Body;
        
        public RetrieveNotificationMessageResponse() {
        }
        
        public RetrieveNotificationMessageResponse(ServiceTest.ServiceReference.RetrieveNotificationMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://app.fpml.org/ws")]
    public partial class RetrieveNotificationMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetrieveNotificationMessageResult;
        
        public RetrieveNotificationMessageResponseBody() {
        }
        
        public RetrieveNotificationMessageResponseBody(string RetrieveNotificationMessageResult) {
            this.RetrieveNotificationMessageResult = RetrieveNotificationMessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebInterfaceSoapChannel : ServiceTest.ServiceReference.WebInterfaceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebInterfaceSoapClient : System.ServiceModel.ClientBase<ServiceTest.ServiceReference.WebInterfaceSoap>, ServiceTest.ServiceReference.WebInterfaceSoap {
        
        public WebInterfaceSoapClient() {
        }
        
        public WebInterfaceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebInterfaceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebInterfaceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebInterfaceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.ServiceReference.StartSessionResponse ServiceTest.ServiceReference.WebInterfaceSoap.StartSession(ServiceTest.ServiceReference.StartSessionRequest request) {
            return base.Channel.StartSession(request);
        }
        
        public bool StartSession(string username, string password) {
            ServiceTest.ServiceReference.StartSessionRequest inValue = new ServiceTest.ServiceReference.StartSessionRequest();
            inValue.Body = new ServiceTest.ServiceReference.StartSessionRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            ServiceTest.ServiceReference.StartSessionResponse retVal = ((ServiceTest.ServiceReference.WebInterfaceSoap)(this)).StartSession(inValue);
            return retVal.Body.StartSessionResult;
        }
        
        public void EndSession() {
            base.Channel.EndSession();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.ServiceReference.SubmitMessageResponse ServiceTest.ServiceReference.WebInterfaceSoap.SubmitMessage(ServiceTest.ServiceReference.SubmitMessageRequest request) {
            return base.Channel.SubmitMessage(request);
        }
        
        public string SubmitMessage(string document) {
            ServiceTest.ServiceReference.SubmitMessageRequest inValue = new ServiceTest.ServiceReference.SubmitMessageRequest();
            inValue.Body = new ServiceTest.ServiceReference.SubmitMessageRequestBody();
            inValue.Body.document = document;
            ServiceTest.ServiceReference.SubmitMessageResponse retVal = ((ServiceTest.ServiceReference.WebInterfaceSoap)(this)).SubmitMessage(inValue);
            return retVal.Body.SubmitMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.ServiceReference.RetrieveMessageResponse ServiceTest.ServiceReference.WebInterfaceSoap.RetrieveMessage(ServiceTest.ServiceReference.RetrieveMessageRequest request) {
            return base.Channel.RetrieveMessage(request);
        }
        
        public string RetrieveMessage(bool wait) {
            ServiceTest.ServiceReference.RetrieveMessageRequest inValue = new ServiceTest.ServiceReference.RetrieveMessageRequest();
            inValue.Body = new ServiceTest.ServiceReference.RetrieveMessageRequestBody();
            inValue.Body.wait = wait;
            ServiceTest.ServiceReference.RetrieveMessageResponse retVal = ((ServiceTest.ServiceReference.WebInterfaceSoap)(this)).RetrieveMessage(inValue);
            return retVal.Body.RetrieveMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.ServiceReference.RetrieveResponseMessageResponse ServiceTest.ServiceReference.WebInterfaceSoap.RetrieveResponseMessage(ServiceTest.ServiceReference.RetrieveResponseMessageRequest request) {
            return base.Channel.RetrieveResponseMessage(request);
        }
        
        public string RetrieveResponseMessage(string requestId, bool wait) {
            ServiceTest.ServiceReference.RetrieveResponseMessageRequest inValue = new ServiceTest.ServiceReference.RetrieveResponseMessageRequest();
            inValue.Body = new ServiceTest.ServiceReference.RetrieveResponseMessageRequestBody();
            inValue.Body.requestId = requestId;
            inValue.Body.wait = wait;
            ServiceTest.ServiceReference.RetrieveResponseMessageResponse retVal = ((ServiceTest.ServiceReference.WebInterfaceSoap)(this)).RetrieveResponseMessage(inValue);
            return retVal.Body.RetrieveResponseMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.ServiceReference.ProcessMessageResponse ServiceTest.ServiceReference.WebInterfaceSoap.ProcessMessage(ServiceTest.ServiceReference.ProcessMessageRequest request) {
            return base.Channel.ProcessMessage(request);
        }
        
        public string ProcessMessage(string message) {
            ServiceTest.ServiceReference.ProcessMessageRequest inValue = new ServiceTest.ServiceReference.ProcessMessageRequest();
            inValue.Body = new ServiceTest.ServiceReference.ProcessMessageRequestBody();
            inValue.Body.message = message;
            ServiceTest.ServiceReference.ProcessMessageResponse retVal = ((ServiceTest.ServiceReference.WebInterfaceSoap)(this)).ProcessMessage(inValue);
            return retVal.Body.ProcessMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.ServiceReference.RetrieveNotificationMessageResponse ServiceTest.ServiceReference.WebInterfaceSoap.RetrieveNotificationMessage(ServiceTest.ServiceReference.RetrieveNotificationMessageRequest request) {
            return base.Channel.RetrieveNotificationMessage(request);
        }
        
        public string RetrieveNotificationMessage(bool wait) {
            ServiceTest.ServiceReference.RetrieveNotificationMessageRequest inValue = new ServiceTest.ServiceReference.RetrieveNotificationMessageRequest();
            inValue.Body = new ServiceTest.ServiceReference.RetrieveNotificationMessageRequestBody();
            inValue.Body.wait = wait;
            ServiceTest.ServiceReference.RetrieveNotificationMessageResponse retVal = ((ServiceTest.ServiceReference.WebInterfaceSoap)(this)).RetrieveNotificationMessage(inValue);
            return retVal.Body.RetrieveNotificationMessageResult;
        }
    }
}
